server:
  port: 9003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/thrivex_db?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: liuyuyang

lyy:
  email:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

  oss:
    accessKey: YlsypGvYxub6VtxlY3S5BrbjEL8VUwbsoDU0szu3
    secretKey: oZqTx69xoOQsazwWbM9IJLGpcJbsR5p9SURATGhH
    bucket: thrive
